import Link from "next/link";
import Image from "next/image";
import { factories, type Locale } from "@/data/landing-page";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

export function FactoryProfile({ factoryId, locale }: { factoryId: string; locale: Locale }) {
  const factory = factories.find((item) => item.id.toLowerCase() === factoryId.toLowerCase());
  if (!factory) return <main className="not-found-panel"><h1>Factory not found</h1><Link href={locale === "vi" ? "/vi/manufacturers" : "/manufacturers"}>Back to manufacturers</Link></main>;
  const vi = locale === "vi";
  const factoryImage = factory.id === "VN-PW-018" ? <Image src="/images/factories/vn-pw-018/exterior.jpg" alt="" fill sizes="220px" /> : null;
  return <><Header locale={locale} /><main className="factory-profile"><section className="profile-hero"><div><p className="eyebrow eyebrow-light">{vi ? "Hồ sơ đối tác sản xuất" : "Manufacturing partner profile"}</p><div className="profile-id">{factory.id}</div><h1>{vi ? "Đối tác sản xuất plywood đã xác minh" : "Verified plywood manufacturing partner"}</h1><p>{factory.location} · {factory.region} Vietnam</p><Link className="button button-light" href={`${vi ? "/vi" : ""}/rfq?factory=${factory.id}`}>{vi ? "Yêu cầu kết nối qua Minsen" : "Connect via Minsen"}<span aria-hidden="true">↗</span></Link></div><div className="profile-mark" aria-hidden="true">{factoryImage}<span>MINSEN</span><strong>✓</strong><small>VERIFIED<br />PARTNER</small></div></section><section className="profile-body"><div className="profile-main"><div className="profile-heading"><p className="eyebrow">{vi ? "Tổng quan nhà máy" : "Factory overview"}</p><h2>{vi ? "Năng lực được chọn theo yêu cầu buyer." : "Capability selected for buyer requirements."}</h2></div><div className="profile-spec-grid"><div><span>{vi ? "Loại hình" : "Factory type"}</span><strong>{vi ? "Nhà sản xuất" : "Manufacturer"}</strong></div><div><span>{vi ? "Hoạt động" : "Years in operation"}</span><strong>{factory.years}+ years</strong></div><div><span>{vi ? "Nhân sự" : "Employees"}</span><strong>{factory.employees}</strong></div><div><span>{vi ? "Công suất tháng" : "Monthly capacity"}</span><strong>{factory.monthlyCapacity}</strong></div></div><div className="profile-block"><h3>{vi ? "Sản phẩm chính" : "Main products"}</h3><div className="profile-tags">{factory.products.map((item) => <span key={item}>{item}</span>)}</div></div><div className="profile-block"><h3>{vi ? "Nguyên liệu và quy cách" : "Materials and specifications"}</h3><p>{factory.materials.join(" · ")} · {factory.thicknessRange}</p></div><div className="profile-block"><h3>{vi ? "Thị trường xuất khẩu" : "Export markets"}</h3><div className="profile-tags">{factory.exportMarkets.map((item) => <span key={item}>{item}</span>)}</div></div></div><aside className="profile-sidebar"><div className="verification-card"><span>✓</span><strong>{vi ? "MINSEN ĐÃ XÁC MINH" : "MINSEN VERIFIED"}</strong><p>{vi ? "Thông tin năng lực được đội ngũ sourcing Minsen xem xét." : "Factory information reviewed by the Minsen sourcing team."}</p></div><div className="profile-score"><p>Minsen sourcing score</p><strong>{factory.score}<small>/5</small></strong><div className="score-line"><span style={{ width: `${factory.score * 20}%` }} /></div><small>{vi ? "Điểm tham khảo dựa trên hồ sơ mẫu" : "Reference score based on sample profile"}</small></div><Link className="button button-primary profile-cta" href={`${vi ? "/vi" : ""}/rfq?factory=${factory.id}`}>{vi ? "Yêu cầu Minsen kết nối" : "Ask Minsen to match"}<span aria-hidden="true">↗</span></Link></aside></section></main><Footer locale={locale} /> </>;
}
