import Link from "next/link";
import Image from "next/image";
import { productCatalog, type Locale } from "@/data/landing-page";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

export function ProductProfile({ slug, locale }: { slug: string; locale: Locale }) {
  const product = productCatalog.find((item) => item.slug === slug); const vi = locale === "vi";
  if (!product) return <main className="not-found-panel"><h1>Product not found</h1><Link href={vi ? "/vi/products" : "/products"}>Back to products</Link></main>;
  const image = product.slug === "natural-veneer" ? "/images/products/product-natural-veneer.jpg" : product.slug === "film-faced-plywood" ? "/images/products/product-film-faced-plywood.jpg" : product.slug === "commercial-plywood" ? "/images/products/product-commercial-plywood.jpg" : undefined;
  return <><Header locale={locale} /><main className="product-profile"><section className="product-profile-hero"><div><p className="eyebrow eyebrow-light">{vi ? product.viName : product.name}</p><h1>{vi ? "Tìm nguồn cung phù hợp cho sản phẩm này." : "Find the right source for this product."}</h1><p>{vi ? "Chia sẻ quy cách và nhu cầu của bạn. Minsen sẽ tìm kiếm trong mạng lưới nhà máy để chọn ra các phương án phù hợp." : "Share your specification and requirements. Minsen will search the manufacturing network and shortlist suitable options."}</p><Link className="button button-light" href={`${vi ? "/vi" : ""}/rfq?product=${product.slug}`}>{vi ? "Gửi yêu cầu sản phẩm" : "Request this product"} ↗</Link></div><div className={`product-profile-art ${product.className}`}>{image && <Image src={image} alt={vi ? product.viName : product.name} fill sizes="(max-width: 820px) 100vw, 400px" />}<strong>{product.name}</strong><span>{product.category}</span></div></section><section className="product-profile-body"><div><p className="eyebrow">{vi ? "Thông tin sản phẩm" : "Product information"}</p><h2>{vi ? product.viName : product.name}</h2><p>{product.description}</p></div><div className="product-profile-spec"><h3>{vi ? "Quy cách tham khảo" : "Reference specifications"}</h3><p>{product.specs}</p><h3>{vi ? "Ứng dụng" : "Typical applications"}</h3><p>{vi ? "Nội thất · Xây dựng · Đóng gói · Trang trí · Sản xuất OEM" : "Furniture · Construction · Packaging · Interior · OEM production"}</p></div></section><section className="product-profile-cta"><p className="eyebrow">{vi ? "Cần quy cách riêng?" : "Need a custom specification?"}</p><h2>{vi ? "Để Minsen tìm nhà máy phù hợp cho bạn." : "Let Minsen find the right factory for you."}</h2><Link className="button button-primary" href={vi ? "/vi/rfq" : "/rfq"}>{vi ? "Bắt đầu RFQ" : "Start an RFQ"} ↗</Link></section></main><Footer locale={locale} /></>;
}
