import Link from "next/link";
import Image from "next/image";
import { productCatalog, type Locale } from "@/data/landing-page";

export function ProductBrowse({ locale }: { locale: Locale }) {
  const vi = locale === "vi";
  const imageFor = (slug: string) => ({ "commercial-plywood": "/images/products/product-commercial-plywood.jpg", "film-faced-plywood": "/images/products/product-film-faced-plywood.jpg", "packing-plywood": "/images/products/product-packing-plywood.jpg", "natural-veneer": "/images/products/product-natural-veneer.jpg", "engineered-veneer": "/images/products/product-engineered-veneer.jpg", lvl: "/images/products/product-lvl.jpg", "mdf-hdf": "/images/products/product-mdf-hdf.jpg", "finger-joint-board": "/images/products/product-finger-joint-board.jpg" }[slug]);
  return <section className="product-browse"><div className="section-heading"><p className="eyebrow">{vi ? "Tìm theo sản phẩm" : "Browse by product"}</p><h2>{vi ? <>Bạn cần gì?<br /><em>Chúng tôi tìm giúp.</em></> : <>Know what you need?<br /><em>Start here.</em></>}</h2></div><div className="browse-grid">{productCatalog.slice(0, 6).map((product) => <Link className="browse-card" href={`${vi ? "/vi" : ""}/products/${product.slug}`} key={product.slug}><div className="browse-art">{imageFor(product.slug) && <Image src={imageFor(product.slug)!} alt={vi ? product.viName : product.name} fill sizes="(max-width: 820px) 100vw, 33vw" />}<span>{product.category}</span><strong>{product.name}</strong></div><p>{vi ? product.viName : product.name}</p><small>{product.specs}</small><span className="browse-arrow" aria-hidden="true">↗</span></Link>)}</div><div className="browse-footer"><p>{vi ? "Không chắc nên bắt đầu từ đâu?" : "Not sure where to start?"}</p><Link className="text-link" href={vi ? "/vi/rfq" : "/rfq"}>{vi ? "Để Minsen tìm nhà máy phù hợp" : "Let Minsen find your supplier"} <span aria-hidden="true">↗</span></Link></div></section>;
}
