"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { factories, type Locale } from "@/data/landing-page";

export function ShortlistPage({ locale }: { locale: Locale }) {
  const vi = locale === "vi"; const [ids, setIds] = useState<string[]>([]);
  useEffect(() => { const timer = window.setTimeout(() => setIds(JSON.parse(window.localStorage.getItem("minsen-shortlist") || "[]")), 0); return () => window.clearTimeout(timer); }, []);
  const selected = factories.filter((factory) => ids.includes(factory.id));
  return <main className="shortlist-page"><section className="shortlist-header"><p className="eyebrow eyebrow-light">{vi ? "Danh sách sourcing của tôi" : "My sourcing list"}</p><h1>{vi ? "Các nhà máy bạn đang cân nhắc." : "Factories you are considering."}</h1><p>{vi ? "Gửi danh sách này cho Minsen để chúng tôi đánh giá và kết nối các lựa chọn phù hợp nhất." : "Send this list to Minsen and we will evaluate and connect the most suitable options."}</p></section><section className="shortlist-content">{selected.length === 0 ? <div className="empty-results"><h2>{vi ? "Danh sách đang trống" : "Your shortlist is empty"}</h2><p>{vi ? "Hãy khám phá mạng lưới nhà máy và lưu các lựa chọn bạn quan tâm." : "Explore the factory network and save the options you are interested in."}</p><Link className="button button-primary" href={vi ? "/vi/manufacturers" : "/manufacturers"}>{vi ? "Khám phá nhà máy" : "Explore manufacturers"} ↗</Link></div> : <><div className="compare-table"><div className="compare-row compare-heading"><strong>{vi ? "Tiêu chí" : "Criteria"}</strong>{selected.map((factory) => <strong key={factory.id}>{factory.id}</strong>)}</div>{[[vi ? "Sản phẩm" : "Products", (factory: typeof selected[number]) => factory.products.slice(0, 2).join(", ")], [vi ? "Nguyên liệu" : "Core", (factory: typeof selected[number]) => factory.materials.join(", ")], [vi ? "Công suất" : "Capacity", (factory: typeof selected[number]) => factory.monthlyCapacity], [vi ? "Thị trường" : "Markets", (factory: typeof selected[number]) => factory.exportMarkets.slice(0, 3).join(", ")], [vi ? "Score" : "Score", (factory: typeof selected[number]) => `${factory.score}/5`]].map(([label, value]) => <div className="compare-row" key={label as string}><span>{label as string}</span>{selected.map((factory) => <span key={factory.id}>{(value as (item: typeof factory) => string)(factory)}</span>)}</div>)}</div><Link className="button button-primary" href={vi ? "/vi/rfq" : "/rfq"}>{vi ? "Yêu cầu Minsen kết nối các nhà máy này" : "Ask Minsen to match these factories"} ↗</Link></>}</section></main>;
}
